name: Check Pull Request Source Branch

on:
  workflow_call:
    inputs:
      base_ref:
        description: The target branch of pull request.
        required: true
        type: string
      head_ref:
        description: The source branch of pull request.
        required: true
        type: string
      wanted_head_ref:
        description: The wanted source branch of the pull request.
        required: true
        type: string

jobs:
  check_source_branch:
    name: Check Source Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          BASE_REF: ${{ inputs.base_ref }}
          HEAD_REF: ${{ inputs.head_ref }}
          WANTED_HEAD_REF: ${{ inputs.wanted_head_ref }}
        with:
          script: |
            const { BASE_REF, HEAD_REF, WANTED_HEAD_REF } = process.env

            if (HEAD_REF !== WANTED_HEAD_REF) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## :exclamation: You can only merge into **\`${ BASE_REF }\`** from **\`${ WANTED_HEAD_REF }\`** not **\`${ HEAD_REF }\`**.

                ### Please create a new pull request with the **\`${ WANTED_HEAD_REF }\`** branch as the source.`
              })

              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                state: "closed"
              })

              core.setFailed()
            } else {
              core.info(`Head ref is ${ WANTED_HEAD_REF }... continuing.`)
            }
