name: Get File Changes

on:
  workflow_call:
    inputs:
      initial-fetch-depth:
        required: false
        type: number
        default: 100
    outputs:
      docs:
        description: "Boolean if docs app changed."
        value: ${{ jobs.get_file_changes.outputs.docs }}
      web:
        description: "Boolean if web app changed."
        value: ${{ jobs.get_file_changes.outputs.web }}
      ui:
        description: "Boolean if ui package changed."
        value: ${{ jobs.get_file_changes.outputs.ui }}

jobs:
  get_file_changes:
    name: Check File Changes
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      web: ${{ steps.filter.outputs.web }}
      ui: ${{ steps.filter.outputs.ui }}
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'push'  }}

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          initial-fetch-depth: ${{ inputs.initial-fetch-depth }}
          filters: |
            docs:
              - 'apps/docs/**'
            web:
              - 'apps/web/**'
            ui:
              - 'packages/ui/**'
