name: Main CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Setup Next.JS cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/apps/*/.next/cache
          key: ${{ github.ref_name }}-nextjs-cache-${{ github.job }}-${{ github.sha }}
          restore-keys: ${{ github.ref_name }}-nextjs-cache-${{ github.job }}-

      - name: Setup .turbo cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.turbo
          key: ${{ github.ref_name }}-turbo-cache-${{ github.job }}-${{ github.sha }}
          restore-keys: ${{ github.ref_name }}-turbo-cache-${{ github.job }}-

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: npm run build:ci
