name: Production

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/ui/**"
      - "**/package-lock.json"

jobs:
  get_file_changes:
    name: What Changed
    needs: check_source_branch
    uses: ./.github/workflows/get-file-changes.yml

  docs:
    name: Docs
    needs: get_file_changes
    if: ${{ needs.get_file_changes.outputs.docs == 'true' || needs.get_file_changes.outputs.ui == 'true' }}
    uses: ./.github/workflows/deploy-app.yml
    with:
      turborepo_filter: "@scope/docs"
      deploy_command: "netlify deploy --build --prod"
      working_directory: "apps/docs"
      environment_name: "production:docs"
      environment_url: "https://testing.ibcarr.com"
    secrets:
      netlify_site_id: ${{ secrets.DOCS_SITE_ID  }}
      netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
