name: Production

on:
  push:
    branches:
      - main

jobs:
  get_file_changes:
    name: What Changed
    uses: ./.github/workflows/get-file-changes.yml

  docs:
    name: Docs
    needs: get_file_changes
    if: ${{ needs.get_file_changes.outputs.docs == 'true' || needs.get_file_changes.outputs.ui == 'true' }}
    uses: ./.github/workflows/deploy-app.yml
    with:
      turborepo_filter: "@scope/docs"
      deploy_flags: "--prod"
      working_directory: "apps/docs"
      environment_name: "Docs Production"
      environment_url: "https://testing.ibcarr.com"
    secrets:
      netlify_site_id: ${{ secrets.DOCS_SITE_ID  }}
      netlify_auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  web:
    name: Web
    needs: get_file_changes
    if: ${{ needs.get_file_changes.outputs.web == 'true' || needs.get_file_changes.outputs.ui == 'true' }}
    runs-on: ubuntu-latest
    environment: "Web Production"
    steps:
      - run: echo "Deploy Web to Production"
