name: Push / Next

on:
  push:
    branches:
      - next

jobs:
  ci:
    name: CI / Code Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --ignore-scripts --prefer-offline --no-audit

      - name: Cache turbo cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules/.cache/turbo
          key: turbo-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            turbo-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
            turbo-cache-${{ runner.os }}-

      - name: Cache .next cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/*/.next/cache
          key: nextjs-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            nextjs-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-
            nextjs-cache-${{ runner.os }}-

      - name: Code Standards
        run: npx turbo run lint
