# https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Deploy to Production on Push to Main

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"

  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci --no-audit
      - run: npm install --save-dev netlify-cli
      - name: Deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.DOCS_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        working-directory: ./apps/docs
        run: netlify deploy --build
