name: Deploy to Production on Push to Main

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci --no-audit
      - uses: netlify/actions/cli@master
        with:
          args: deploy --build
        env:
          NETLIFY_SITE_ID: ${{ secrets.DOCS_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
