name: Deploy to Staging on Pull Request to Main

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"

  workflow_dispatch:

jobs:
  check_source_branch:
    name: Check Source Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.pull_request.head.ref !== "next") {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `## :exclamation: You can only merge into **\`main\`** from **\`next\`** not **\`${ context.payload.pull_request.head.ref}\`**.

                ### Please create a new pull request with the **\`next\`** branch as the source.`
              });

              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                state: "closed"
              });

              core.setFailed();
            } else {
              core.info("Head ref is next... continuing.");
            }
  get_changes:
    needs: check_source_branch
    if: success()
    name: Check File Changes
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      web: ${{ steps.filter.outputs.web }}
      packages: ${{ steps.filter.outputs.packages }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'apps/docs/**'
            web:
              - 'apps/web/**'
            packages:
              - 'packages/**'
  # do full build of monorepo. upload .next folder after build for each app
  # - always build monorepo no matter what changed. if nothing changed then it should >>> FULL TURBO <<<
  # - this way we can cache .npm folder after npm ci to hopefully speed up install
  # - and .turbo and .next folders after build
  # - and also this way we can split all this crap into seperate workflow files
  # - and only netlify deploy --build the changed apps
  # - https://docs.github.com/en/actions/using-workflows/reusing-workflows
  build_and_deploy_docs:
    needs: get_changes
    name: Build and Deploy Docs
    if: ${{ needs.get_changes.outputs.docs == 'true' || needs.get_changes.outputs.packages == 'true' }}
    environment:
      name: staging
      url: https://staging--ibcarr-testing.netlify.app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache .npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ github.head_ref }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ github.head_ref }}-npm-

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Install netlify-cli
        run: npm install --save-dev netlify-cli

      - name: Cache .next cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/docs/.next/cache
          key: ${{ github.head_ref }}-docs-nextjs-${{ hashFiles('package-lock.json') }}-${{ hashFiles('**.[jt]s', '**[jt]sx') }}
          restore-keys: ${{ github.head_ref }}-docs-nextjs-${{ hashFiles('package-lock.json') }}-

      - name: Build
        run: turbo run build --cache-dir=.turbo --filter=@scope/docs

      - name: Deploy
        env:
          NETLIFY_SITE_ID: ${{ secrets.DOCS_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        working-directory: ./apps/docs
        run: netlify deploy --build --alias staging

      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## :heavy_check_mark: Pull Request Preview: **Docs**.

              ### This pull request preview for **\`docs\`** can be found [here](https://staging--ibcarr-testing.netlify.app).`
            });
