name: Deploy to Production on Push to Main

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"

  workflow_dispatch:

jobs:
  cry:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'TODO: Add this workflow to work correctly'"
