name: Test A

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy docs website
      - run: echo ${{github.base_ref}}
      - run: echo ${{github.head_ref}}
