name: Test

on: issues

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.action }}
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
