name: Test

on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event.issue) }}
      - run: echo ${{ github.event.label.name }}
