name: Test Deploy

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"

jobs:
  check_changes:
    runs-on: ubuntu-latest
    # if: github.head_ref == "staging"
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            docs:
              - 'apps/docs/**'
            web:
              - 'apps/web/**'
  deploy_docs:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.docs == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'checkout repo'
      - run: echo 'pull caches'
      - run: echo 'npx turbo --filter=@scope/docs'
      - run: echo 'install deps'
      - run: echo 'lint & format'
      - run: echo 'deploy'
  deploy_web:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.web == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'checkout repo'
      - run: echo 'pull caches'
      - run: echo 'npx turbo --filter=@scope/web'
      - run: echo 'install deps'
      - run: echo 'lint & format'
      - run: echo 'deploy'
