on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la ~
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: ls -la ~
      - run: npm ci --ignore-scripts --prefer-offline --no-audit
      - run: ls -la ~
